services:
  - type: web
    name: pagemind-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
       -key: GEMINI_API_KEY
        sync: false   # then set the value manually in the Render dashboard
    healthCheckPath: /health
